
typeofliquor = input("Enter a type of liquor: ")
occupation = input("Enter an occupation: ")
animals_plural = input("enter plural animals: ")
food = input("enter type of food: ")
underweartype = input("enter type of underwear: ")
cartoon_char = input("enter cartoon char: ")
animal = input("enter animal: ")
swearword = input("enter an swearword: ")
color = input("enter a color: ")
noun = input("enter a noun: ")
condiment = input("enter a condiment: ")
swearword2 = input("enter another swearword: ")
bodypart = input("enter a bodypart: ")
candy = input("enter a candy: ")
snack = input("enter a snack: ")
sport = input("enter a sport: ")
religious_figures = input("enter religious figures plural: ")
toy = input("enter a toy: ")
swearword3 = input("enter a swearword: ")
noun2 = input("enter a noun: ")
profession = input("enter a profession: ")
business_name = input("enter a business neame: ")

print("Today I Quit My Job")
print("After drinking an 8 gallon drum of " + typeofliquor + " I decided it was time to quit my job as a/an " + occupation + ". Considering I was being paid in " + animals_plural + " and " + food + ", I had enough!")
print("The day I quit, I decided to only wear " + underweartype + " to the office. This was the real me and I wanted Mr. " + cartoon_char + " to see all of it! I thought, ‘screw it’! I’m going out with a bang! Just before leaving the house, my pet " + animal + " looked up at me and I didn’t know if he was thinking ‘" + swearword + "’ or ‘I want to hump that! Before he had time to decide, I ran out and jumped on to my trusty " + animal + " and sped off.")
print("Mr. " + cartoon_char + ", was out to lunch. I went into his office and sat my " + color + " ass on his " + noun + " and waited. After about 20 minutes he returned, with a little bit of " + condiment + " on his chin.")
print("“Why are you only in your " + underweartype + "” He asked.")
print("“Because I don’t give a " + swearword2 + " anymore and I have something to tell you!” I declared, throwing my hand in the air.")
print("I stood up and put my "+ bodypart +" on his desk for drama.")
print("“Listen up! I don’t appreciate being treated like " + candy + "! You’re as dumb as a " + snack + "! I would rather play " + sport + " with a team of " + religious_figures + ", then work 1 more day with you!”")
print("For added drama, I then swiped my arm across his desk, knocking everything over, including his " + toy + ".")
print("I declared, “I quit this bitch! " + swearword3 + " you and " + swearword + " your stupid " + noun2 + "!”")
print("I walked out and for added drama, I knocked over the " + noun + " in the lobby.")
print("Tomorrow, I’m applying to be a " + profession + " at " + business_name + ".")