import os

# REQUIRED APIs
SHEETY_BEARER_TOKEN = os.environ["SHEETY_BEARER_TOKEN"]
SHEETY_USERID = "720b14bb86924f26582e95ebbab971fa"
SHEETY_PROJECT_DIR = "flightDeals/prices"
SHEETY_API_ENDPOINT = f"https://api.sheety.co/{SHEETY_USERID}/{SHEETY_PROJECT_DIR}"

TEQUILA_FLIGHT_SEARCH_API_KEY = 0  # os.environ["TEQUILA_FLIGHT_SEARCH_API_KEY"]

